---
- name: rake db:migrate
  become_user: vagrant
  shell: bash -lc 'RAILS_ENV={{item}} bundle exec rake db:migrate'
  args:
    chdir: /vagrant
  with_items: "{{environments}}"

- name: load seeds
  become_user: vagrant
  shell: bash -lc 'bundle exec rake db:seed'
  args:
    chdir: /vagrant
